# il faut modifier le password du root dans MySQL
# commandes Mysql déplacées de init vers command
# car sinon le serveur MySQL n'a pas le temps de démarrer
# avant l'execution des commandes


# MySQL
image: gitpod/workspace-mysql

tasks:
  - init:
      sdk use java 17.0.5.fx-zulu
      ./mvnw clean install -U -DskipTests
    command:
      sdk use java 17.0.5.fx-zulu
      mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'mypassword';"
      mysql -u root -e "create database 2itech_demo";
      ./mvnw spring-boot:run
    name: Run webapp

ports:
  #SpringBoot
  - port: 8080
    onOpen: open-preview
  # MySQL
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack