# MySQL
image: gitpod/workspace-mysql

tasks:
  - init:
      sdk use java 17.0.5.fx-zulu
      mysql -u root -e "create database 2itech_demo";
      ./mvnw clean install -U -DskipTests
    command: ./mvnw spring-boot:run
    name: Run webapp

ports:
  #SpringBoot
  - port: 8080
    onOpen: open-preview
  # MySQL
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack